# Generated by Django 5.0.7 on 2024-08-03 10:02

import django.utils.timezone
import django_resized.forms
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PURGATORIUM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='authors/favicon_black.png', force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='authors'),
        ),
    ]
