# Generated by Django 5.0.7 on 2024-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PURGATORIUM', '0002_category_description_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
